version: '3.1'

services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data=/var/lib/mysql
        
  app:
    container_name: zeroboom-bot
    build: .